#!/bin/python3.12
from os import system

s = []
with open('num.txt', 'r') as f:
    for line in f:
        # print(line.strip())
        s.append(line.split('\n')) 

s = s[0][0]
s = int(s)

while True:
    play = f'"C:/Program Files/VideoLAN/VLC/vlc.exe" -f ./02/js-{s}.mp4'
    system(play)
    i = str(input('\n\n\n\n\n\n\n\n\n\n                    Next or Quit or Replay ? ( n | q | r | p ) : '))
    if i == 'q':
        system('rm ./num.txt')
        writer = f'echo {s} > num.txt'
        system(writer)
        break
    elif i == 'n':
        s += 1 
    elif i == 'p':
        s -= 1
    elif i == 'i':
        pass